[package]
name = "vdp-halo2-verifiable-randomness"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = "0.13"
halo2_gadgets = "0.5"
halo2_proofs = "0.3"
num-bigint = "0.4"
pasta_curves = "0.5"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
sha2 = "0.10"

[profile.release]
lto = "thin"
